//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hornet.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HornetModelContainer : DbContext
    {
        public HornetModelContainer()
            : base("name=HornetModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HashGroup> HashGroups { get; set; }
        public virtual DbSet<HashEntry> HashEntries { get; set; }
        public virtual DbSet<RegexGroup> RegexGroups { get; set; }
        public virtual DbSet<RegexEntry> RegexEntries { get; set; }
    }
}
